### ISSUE TITLE
Change production reverse proxy from Caddy to nginx with static configuration and host network mode (much better performance)

### ISSUE THREAD

**Issue by Jblew** [noisy-witness/wise-caddy#1]

**Comment by noisy** [comment]
- Documentation should be moved to https://docs.wise.vote/
- All trafic from https://hub.wise.vote/ should be redirected to https://wise.vote/
  - also, for example https://hub.wise.vote/@noisy to https://wise.vote/@noisy, etc...

**Comment by noisy** [comment]
@Jblew please remember about updating urls in different places, like:

![selection_999 629](https://user-images.githubusercontent.com/201263/49566049-a4e13c80-f929-11e8-8d09-419a018e6f19.png)

![selection_999 631](https://user-images.githubusercontent.com/201263/49566263-58e2c780-f92a-11e8-9212-adf7529c4cd8.png)

**Comment by Jblew** [comment]
Done. Works like charm on staging
